name = "Mossys World"
author = "Mossy Stone"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f49e5a898f06a8f7246b6b4536f1c672242b6a474ee6ed924a7e149d94438fce"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
