name = "Mossys World"
author = "Mossy Stone"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd4ac2afa7263734a4b44b4bd043d9f6abbfa57d069e2e030ebb9bdf2a6f87eb"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
