name = "Mossys World"
author = "Mossy Stone"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ebc6f5cb64a10768b8e3342463e84c5163eac6b5ab9caabd80419fe6f017058"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
